### ISSUE TITLE
请问一下demo的代码是什么命令打包出来了？

### ISSUE THREAD

**Issue by mrxu0** [nemo-tree/vue2-shop#7]

**Comment by zw231212** [comment]
demo，应该就是npm run build编译出来的吧，只是他在.gitignore里面把dist目录给忽略了，所以传上来的就没有dist目录，而作者把他自己编译出来好的放在新建的demo目录下。。。。

**Comment by xuxchao** [comment]
> demo，应该就是npm run build编译出来的吧，只是他在.gitignore里面把dist目录给忽略了，所以传上来的就没有dist目录，而作者把他自己编译出来好的放在新建的demo目录下。。。。

demo里面的不需要启动服务也能够访问，用build打包的不启动服务里面的资源会乱套。应该不是直接build打包出来的

**Comment by zw231212** [comment]
> > demo，应该就是npm run build编译出来的吧，只是他在.gitignore里面把dist目录给忽略了，所以传上来的就没有dist目录，而作者把他自己编译出来好的放在新建的demo目录下。。。。
> 
> demo里面的不需要启动服务也能够访问，用build打包的不启动服务里面的资源会乱套。应该不是直接build打包出来的

你试试build，build出来里面的你直接打开也是没问题的

**Comment by xuxchao** [comment]
> > > demo，应该就是npm run build编译出来的吧，只是他在.gitignore里面把dist目录给忽略了，所以传上来的就没有dist目录，而作者把他自己编译出来好的放在新建的demo目录下。。。。
> > 
> > 
> > demo里面的不需要启动服务也能够访问，用build打包的不启动服务里面的资源会乱套。应该不是直接build打包出来的
> 
> 你试试build，build出来里面的你直接打开也是没问题的

我试过，不行

**Comment by zw231212** [comment]
> > > > demo，应该就是npm run build编译出来的吧，只是他在.gitignore里面把dist目录给忽略了，所以传上来的就没有dist目录，而作者把他自己编译出来好的放在新建的demo目录下。。。。
> > > 
> > > 
> > > demo里面的不需要启动服务也能够访问，用build打包的不启动服务里面的资源会乱套。应该不是直接build打包出来的
> > 
> > 
> > 你试试build，build出来里面的你直接打开也是没问题的
> 
> 我试过，不行

![image](https://user-images.githubusercontent.com/12821929/50952774-6cb2b800-14ec-11e9-9ad1-26dfb155378a.png)

**Comment by xuxchao** [comment]
> > > > > demo，应该就是npm run build编译出来的吧，只是他在.gitignore里面把dist目录给忽略了，所以传上来的就没有dist目录，而作者把他自己编译出来好的放在新建的demo目录下。。。。
> > > > 
> > > > 
> > > > demo里面的不需要启动服务也能够访问，用build打包的不启动服务里面的资源会乱套。应该不是直接build打包出来的
> > > 
> > > 
> > > 你试试build，build出来里面的你直接打开也是没问题的
> > 
> > 
> > 我试过，不行
> 
> ![image](https://user-images.githubusercontent.com/12821929/50952774-6cb2b800-14ec-11e9-9ad1-26dfb155378a.png)

我刚才又重新试了一下确实是可以。可我正常build出来的包都是不能够这样直接访问的。很奇怪

**Comment by xuxchao** [comment]
谢谢你。

**Comment by zw231212** [comment]
@mrxu0 你试试把你项目编译出来的html文件里的css和js绝对路径改为相对路径，也许就可以了。
![image](https://user-images.githubusercontent.com/12821929/50953383-26f6ef00-14ee-11e9-984b-e6f770c1ee04.png)

**Comment by xuxchao** [comment]
> @mrxu0 你试试把你项目编译出来的html文件里的css和js绝对路径改为相对路径，也许就可以了。
> ![image](https://user-images.githubusercontent.com/12821929/50953383-26f6ef00-14ee-11e9-984b-e6f770c1ee04.png)

路径是对了，但是index.html页面提示“We're sorry but vue-shop doesn't work properly without JavaScript enabled. Please enable it to continue.”

**Comment by xuxchao** [comment]
https://github.com/mrxu0/vue-ylbs-shop 这是项目地址，你可以去看一下

**Comment by zw231212** [comment]
> https://github.com/mrxu0/vue-ylbs-shop 这是项目地址，你可以去看一下

你这个应该是编译的问题吧，你的编译的脚本应该有问题

**Comment by xuxchao** [comment]
哥们方便加个Q，微信的么
